version: '3'
services:

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data/:/home/muhal-backend/muhal/data/
      - web-django:/home/muhal-backend/muhal/static
      - web-django:/home/muhal-backend/muhal/static/media
    command: pipenv run gunicorn -b 0.0.0.0:8000 muhal.wsgi
    ports: 
      - "8000:8000"
    env_file: 
      - .env

volumes: 
  web-static:
  web-django: