version: "3"
services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
    #   - ${PWD}/backend/data/muhal_data.sqlite3:/home/muhal-backend/muhal/muhal/muhal_data.sqlite3
    command: ./start.sh
    expose:
      - "8000"
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.backend=backend
      - traefik.docker.network=web
      - traefik.port=8000
      - "traefik.http.routers.muhal-api.rule=Host(`${PROJECT_URL}`) && PathPrefix(`/api/`, `/admin/`, `/static/`, `/{locale:[a-z]{2}}/admin/`)"
    networks:
      - private

  client:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.backend=client
      - traefik.docker.network=web
      - traefik.port=3000
      - "traefik.http.routers.muhal-client.rule=Host(`${PROJECT_URL}`) && PathPrefix(`/`, `/{locale:[a-z]{2}}/`, `/_nuxt/`)"
    networks:
      - private

  traefik:
    image: traefik:2.2
    container_name: traefik
    restart: always
    hostname: traefik
    security_opt:
      - no-new-privileges:false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/traefik.yml:ro"
    labels:
      - "traefik.enable=true"
    networks:
      - private
      - web
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    depends_on:
      - backend
      - client

networks:
  private:
    external: false
  web:
    external: true
