version: '3'
services:

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data/:/home/muhal-backend/muhal/data/
      - web-static:/home/muhal-backend/muhal/static
    command: ./start.sh
    # ports: 
    #   - "8000:8000"
    expose: 
      - "8000"
    env_file: 
      - .env

  nginx:
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    command: /bin/sh -c "envsubst '$${PROJECT_ROOT}' < /tmp/muhal.conf.template > /etc/nginx/conf.d/muhal.conf && cat /etc/nginx/conf.d/muhal.conf && exec nginx -g 'daemon off;'"
    env_file: 
      - .env
    depends_on: 
      - backend

volumes: 
  web-static: