## traefik.yml

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

## Static configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: ":443"

# Configuration of certificate resolvers
certificatesResolvers:
  leresolver:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      email: "majd@smex.com"
      storage: "/acme.json"
      tlsChallenge: {}

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

# Configuration for Traefik logs
log:
  filePath: "/etc/traefik/log/traefik.log"
  # format: json
  format: common
  level: DEBUG

# Configuration for Traefik access logs
accessLog:
  filePath: "/etc/traefik/log/access.log"
  format: json
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"

http:
#   routers:
#     client-router:
#       rule: "Host(`${PROJECT_URL}`) && PathPrefix(`/`, `/{locale:[a-z]{2}}/`, `/_nuxt/`)"
#       service: client
#     backend-router:
#       rule: "Host(`${PROJECT_URL}`) && PathPrefix(`/api/`, `/admin/`, `/static/`, `/{locale:[a-z]{2}}/admin/`)"
#       service: backend
#       tls:
#         certResolver: "leresolver"
#         domains:
#           - main: "beta.muhal.org"